# Generated by Django 3.2.8 on 2021-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[(1, 'Back-End'), (2, 'Front-End'), (3, 'iOS'), (4, 'Android')],
                                   default=1, max_length=1),
            preserve_default=False,
        ),
    ]
