# Generated by Django 3.2.8 on 2021-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[(1, 'Creator'), (2, 'Manager'), (3, 'Author')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[(1, 'Todo'), (2, 'Handled'), (3, 'Closed')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[(1, 'Bug'), (2, 'Feature'), (3, 'Task')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(max_length=128),
        ),
    ]
