# Generated by Django 3.2.8 on 2021-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211110_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Creator', 'Creator'), ('Manager', 'Manager'), ('Author', 'Author')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Handled', 'Handled'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Task', 'Task')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Back-End', 'Back-End'), ('Front-End', 'Front-End'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=10),
        ),
    ]
